Repository kubernetes-client/csharp, pull requests merged in 2018-09, with the labels that each got.

#200 Xamarin support
  src/KubernetesClient/Kubernetes.ConfigInit.cs
  src/KubernetesClient/KubernetesClient.csproj
  src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs
Labels: approved, cncf-cla: yes, lgtm, size/L

#201 Update install-linux.sh
  install-linux.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#203 align files to .editorconfig
  examples/attach/Attach.cs
  examples/labels/PodList.cs
  examples/namespace/Namespace.cs
  examples/simple/PodList.cs
  examples/watch/Program.cs
  src/KubernetesClient/Exceptions/KubeConfigException.cs
  src/KubernetesClient/Exceptions/KubernetesClientException.cs
  src/KubernetesClient/Fractions/Extensions/MathExt.cs
  src/KubernetesClient/Fractions/Formatter/DefaultFractionFormatProvider.cs
  src/KubernetesClient/Fractions/Formatter/DefaultFractionFormatter.cs
  src/KubernetesClient/Fractions/Fraction.CompareTo.cs
  src/KubernetesClient/Fractions/Fraction.Constructors.cs
  src/KubernetesClient/Fractions/Fraction.ConvertFrom.cs
  src/KubernetesClient/Fractions/Fraction.ConvertTo.cs
  src/KubernetesClient/Fractions/Fraction.Equality.cs
  src/KubernetesClient/Fractions/Fraction.Math.cs
  src/KubernetesClient/Fractions/Fraction.Operators.cs
  src/KubernetesClient/Fractions/Fraction.ToString.cs
  src/KubernetesClient/Fractions/Fraction.cs
  src/KubernetesClient/Fractions/FractionState.cs
  src/KubernetesClient/Fractions/InvalidNumberException.cs
  src/KubernetesClient/Fractions/TypeConverters/FractionTypeConverter.cs
  src/KubernetesClient/IKubernetes.Watch.cs
  src/KubernetesClient/IKubernetesObject.cs
  src/KubernetesClient/IntstrIntOrString.cs
  src/KubernetesClient/KubeConfigModels/AuthProvider.cs
  src/KubernetesClient/KubeConfigModels/Cluster.cs
  src/KubernetesClient/KubeConfigModels/ClusterEndpoint.cs
  src/KubernetesClient/KubeConfigModels/Context.cs
  src/KubernetesClient/KubeConfigModels/ContextDetails.cs
  src/KubernetesClient/KubeConfigModels/K8SConfiguration.cs
  src/KubernetesClient/KubeConfigModels/User.cs
  src/KubernetesClient/KubeConfigModels/UserCredentials.cs
  src/KubernetesClient/Kubernetes.ConfigInit.cs
  src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs
  src/KubernetesClient/KubernetesClientConfiguration.InCluster.cs
  src/KubernetesClient/KubernetesClientConfiguration.cs
  src/KubernetesClient/KubernetesObject.cs
  src/KubernetesClient/ResourceQuantity.cs
  src/KubernetesClient/V1Status.ObjectView.cs
  src/KubernetesClient/Watcher.cs
  src/KubernetesClient/WatcherDelegatingHandler.cs
  tests/KubernetesClient.Tests/AssemblyInfo.cs
  tests/KubernetesClient.Tests/AuthTests.cs
  tests/KubernetesClient.Tests/CertUtilsTests.cs
  tests/KubernetesClient.Tests/IntOrStringTests.cs
  tests/KubernetesClient.Tests/KubernetesClientConfigurationTests.cs
  tests/KubernetesClient.Tests/QuantityValueTests.cs
  tests/KubernetesClient.Tests/V1StatusObjectViewTests.cs
  tests/KubernetesClient.Tests/WatchTests.cs
  tests/KubernetesClient.Tests/YamlTests.cs
Labels: cncf-cla: yes, size/XXL
