Repository kubernetes-client/csharp, pull requests merged in 2018-06, with the labels that each got.

#177 fix test case fail on windows
  tests/KubernetesClient.Tests/AuthTests.cs
  tests/KubernetesClient.Tests/YamlTests.cs
Labels: cncf-cla: yes, size/M

#178 Extra tests for the Watcher classes
  tests/KubernetesClient.Tests/WatchTests.cs
Labels: cncf-cla: yes, size/L

#180 add SECURITY_CONTACTS
  SECURITY_CONTACTS
Labels: cncf-cla: yes, size/S

#184 Watcher: notify the caller when the server closes the connection
  gen/KubernetesWatchGenerator/IKubernetes.Watch.cs.template
  gen/KubernetesWatchGenerator/Kubernetes.Watch.cs.template
  src/KubernetesClient/IKubernetes.Watch.cs
  src/KubernetesClient/Kubernetes.Watch.cs
  src/KubernetesClient/Watcher.cs
  src/KubernetesClient/generated/IKubernetes.Watch.cs
  src/KubernetesClient/generated/Kubernetes.Watch.cs
  tests/KubernetesClient.Tests/WatchTests.cs
Labels: cncf-cla: yes, size/XL
