Repository kubernetes-client/csharp, pull requests merged in 2018-07, with the labels that each got.

#185 Use the Git height as the third component in the version number
  version.json
Labels: cncf-cla: yes, size/XS

#188 Always add client certificates if present.
  src/KubernetesClient/Kubernetes.ConfigInit.cs
Labels: cncf-cla: yes, size/XS

#189 add patch example
  examples/patch/Program.cs
  examples/patch/patch.csproj
  kubernetes-client.sln
Labels: cncf-cla: yes, size/M

#190 Update WatcherDelegatingHandler to stop eating first line (#183)
  src/KubernetesClient/WatcherDelegatingHandler.cs
  tests/KubernetesClient.Tests/WatchTests.cs
Labels: cncf-cla: yes, size/M

#191 Update tests namespaces for consistency
  tests/KubernetesClient.Tests/CertificateValidationTests.cs
  tests/KubernetesClient.Tests/WatcherTests.cs
Labels: cncf-cla: yes, size/XS

#192 Release version 1.2.0
  version.json
Labels: cncf-cla: yes, size/XS

#194 Move Fractions library inside project
  src/KubernetesClient/Fractions/Extensions/MathExt.cs
  src/KubernetesClient/Fractions/Formatter/DefaultFractionFormatProvider.cs
  src/KubernetesClient/Fractions/Formatter/DefaultFractionFormatter.cs
  src/KubernetesClient/Fractions/Fraction.CompareTo.cs
  src/KubernetesClient/Fractions/Fraction.Constructors.cs
  src/KubernetesClient/Fractions/Fraction.ConvertFrom.cs
  src/KubernetesClient/Fractions/Fraction.ConvertTo.cs
  src/KubernetesClient/Fractions/Fraction.Equality.cs
  src/KubernetesClient/Fractions/Fraction.Math.cs
  src/KubernetesClient/Fractions/Fraction.Operators.cs
  src/KubernetesClient/Fractions/Fraction.ToString.cs
  src/KubernetesClient/Fractions/Fraction.cs
  src/KubernetesClient/Fractions/FractionState.cs
  src/KubernetesClient/Fractions/InvalidNumberException.cs
  src/KubernetesClient/Fractions/README.md
  src/KubernetesClient/Fractions/TypeConverters/FractionTypeConverter.cs
  src/KubernetesClient/Fractions/license.txt
  src/KubernetesClient/KubernetesClient.csproj
Labels: cncf-cla: yes, size/XXL

#193 Add support for 'azure' AAD based authentication.
  src/KubernetesClient/KubeConfigModels/AuthProvider.cs
  src/KubernetesClient/KubeConfigModels/UserCredentials.cs
  src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs
  tests/KubernetesClient.Tests/KubernetesClientConfigurationTests.cs
Labels: cncf-cla: yes, size/L
