Repository kubernetes-client/csharp, pull requests merged in 2019-03, with the labels that each got.

#247 add az pipepline yaml
  .azure-pipelines.yaml
  src/KubernetesClient/KubernetesClient.csproj
  tests/KubernetesClient.Tests/KubernetesClient.Tests.csproj
  version.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#251 Improve the default client loading code.
  examples/simple/PodList.cs
  src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs
  src/KubernetesClient/KubernetesClientConfiguration.InCluster.cs
Labels: approved, cncf-cla: yes, lgtm, size/M

#252 generator cmd param
  gen/KubernetesWatchGenerator/Program.cs
Labels: approved, cncf-cla: yes, lgtm, size/M

#253 Add bundle certificate support
  src/KubernetesClient/CertUtils.cs
  src/KubernetesClient/Kubernetes.ConfigInit.cs
  src/KubernetesClient/Kubernetes.WebSocket.cs
  src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs
  src/KubernetesClient/KubernetesClientConfiguration.InCluster.cs
  src/KubernetesClient/KubernetesClientConfiguration.cs
  src/KubernetesClient/WebSocketBuilder.cs
  tests/KubernetesClient.Tests/AuthTests.cs
  tests/KubernetesClient.Tests/CertUtilsTests.cs
  tests/KubernetesClient.Tests/CertificateValidationTests.cs
  tests/KubernetesClient.Tests/KubernetesClientConfigurationTests.cs
  tests/KubernetesClient.Tests/assets/ca-bundle-intermediate.crt
  tests/KubernetesClient.Tests/assets/ca-bundle-root.crt
  tests/KubernetesClient.Tests/assets/ca-bundle.crt
Labels: approved, cncf-cla: yes, lgtm, size/L

#255 Re-add nerdbank while we setup the azure pipeline...
  src/KubernetesClient/KubernetesClient.csproj
  version.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#256 Rev to 1.5
  version.json
Labels: approved

#257 Fix NuGet package versions
  .travis.yml
  src/KubernetesClient/KubernetesClient.csproj
Labels: approved, cncf-cla: yes, lgtm, size/XS

#258 Make MSBuild.Sdk.Extras private, it is a build-time only dependency.
  src/KubernetesClient/KubernetesClient.csproj
Labels: approved, cncf-cla: yes, lgtm, size/XS

#259 Fix build warnings in the StreamDemuxerTests
  src/KubernetesClient/StreamDemuxer.cs
  tests/KubernetesClient.Tests/Mock/MockWebSocket.cs
  tests/KubernetesClient.Tests/StreamDemuxerTests.cs
Labels: approved, cncf-cla: yes, lgtm, size/M

#260 Update NuGet dependencies for the Tests project
  tests/KubernetesClient.Tests/KubernetesClient.Tests.csproj
Labels: approved, cncf-cla: yes, lgtm, size/S

#261 Update CI dependencies
  .travis.yml
  install-linux.sh
  install-osx.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#265 Mark all Fractions classes as internal
  src/KubernetesClient/Fractions/Extensions/MathExt.cs
  src/KubernetesClient/Fractions/Formatter/DefaultFractionFormatProvider.cs
  src/KubernetesClient/Fractions/Formatter/DefaultFractionFormatter.cs
  src/KubernetesClient/Fractions/Fraction.CompareTo.cs
  src/KubernetesClient/Fractions/Fraction.Constructors.cs
  src/KubernetesClient/Fractions/Fraction.ConvertFrom.cs
  src/KubernetesClient/Fractions/Fraction.ConvertTo.cs
  src/KubernetesClient/Fractions/Fraction.Equality.cs
  src/KubernetesClient/Fractions/Fraction.Math.cs
  src/KubernetesClient/Fractions/Fraction.Operators.cs
  src/KubernetesClient/Fractions/Fraction.ToString.cs
  src/KubernetesClient/Fractions/Fraction.cs
  src/KubernetesClient/Fractions/FractionState.cs
  src/KubernetesClient/Fractions/InvalidNumberException.cs
  src/KubernetesClient/Fractions/TypeConverters/FractionTypeConverter.cs
  src/KubernetesClient/ResourceQuantity.cs
Labels: approved, cncf-cla: yes, lgtm, size/M

#266 Add MSBuild leg, for building NuGet package with Xamarin support
  .azure-pipelines.yaml
  src/KubernetesClient/KubernetesClient.csproj
Labels: approved, cncf-cla: yes, lgtm, size/M

#267 Add SourceLink support
  src/KubernetesClient/KubernetesClient.csproj
Labels: approved, cncf-cla: yes, lgtm, size/XS

#268 Use YamlDotNet 6.0.0, which is signed by default
  src/KubernetesClient/KubernetesClient.csproj
Labels: approved, cncf-cla: yes, lgtm, size/XS

#250 Improve README.md with better example and descriptions.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#269 fixed BuildConfigFromConfigFile ignoring the currentContext parameter
  src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs
Labels: approved, cncf-cla: yes, lgtm, size/XS

#270 Remove double "Usage" in docs
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#264 Add code coverage, Linux & macOS leg to Azure CI
  .azure-pipelines.yaml
  ci.sh
  install-linux.sh
Labels: cncf-cla: yes, size/L

#274 Temporarily disable the Resharper checks
  .azure-pipelines.yaml
Labels: cncf-cla: yes, size/S
