Repository kubernetes-client/csharp, pull requests merged in 2020-01, with the labels that each got.

#342 Use `Path.DirectorySeparatorChar` to have ServiceAccountPath start from root
  src/KubernetesClient/KubernetesClientConfiguration.InCluster.cs
Labels: approved, cncf-cla: yes, lgtm, size/XS

#336 Prevent NullReferenceException when using HttpClient to initialize Kubernetes client. Fixes #335
  examples/httpClientFactory/Program.cs
  src/KubernetesClient/Kubernetes.ConfigInit.cs
  src/KubernetesClient/KubernetesClientConfiguration.HttpClientHandler.cs
Labels: approved, cncf-cla: yes, lgtm, size/M

#344 Add a loadAll to load multiple objects from a single YAML. (and tests)
  examples/yaml/Program.cs
  examples/yaml/yaml.csproj
  src/KubernetesClient/Yaml.cs
  tests/KubernetesClient.Tests/YamlTests.cs
Labels: approved, cncf-cla: yes, lgtm, size/L

#348 File.Open changed to File.OpenRead
  src/KubernetesClient/Yaml.cs
Labels: approved, cncf-cla: yes, lgtm, size/XS

#350 Updated Nerdbank.GitVersioning to 3.0.50
  src/KubernetesClient/KubernetesClient.csproj
Labels: approved, cncf-cla: yes, lgtm, size/XS
