Repository kubernetes-client/csharp, pull requests merged in 2020-05, with the labels that each got.

#443 Use invariant culture when parsing fractions
  src/KubernetesClient/ResourceQuantity.cs
Labels: cncf-cla: yes, lgtm, size/XS

#442 Quoted non-string values remain quoted after serialization
  src/KubernetesClient/StringQuotingEmitter.cs
  src/KubernetesClient/Yaml.cs
  tests/KubernetesClient.Tests/YamlTests.cs
Labels: approved, cncf-cla: yes, lgtm, size/M

#444 Fix reading incorrect stream in ExecuteExternalCommand
  src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs
Labels: approved, cncf-cla: yes, lgtm, size/XS

#440 add TokenFileAUth which reloads token if it expires
  src/KubernetesClient/Authentication/TokenFileAuth.cs
  src/KubernetesClient/KubernetesClientConfiguration.InCluster.cs
  tests/KubernetesClient.Tests/TokenFileAuth.cs
  tests/KubernetesClient.Tests/assets/token1
  tests/KubernetesClient.Tests/assets/token2
Labels: approved, cncf-cla: yes, lgtm, size/M

#405 Add convenient model extensions
  src/KubernetesClient/ModelExtensions.cs
  tests/KubernetesClient.Tests/ModelExtensionTests.cs
Labels: approved, cncf-cla: yes, lgtm, size/XL

#420 Support for conversions between models of different versions
  gen/KubernetesWatchGenerator/KubernetesWatchGenerator.csproj
  gen/KubernetesWatchGenerator/ModelOperators.cs.template
  gen/KubernetesWatchGenerator/Program.cs
  gen/KubernetesWatchGenerator/VersionConverter.cs.template
  src/KubernetesClient/Extensions.cs
  src/KubernetesClient/KubernetesClient.csproj
  src/KubernetesClient/Versioning/KubernetesVersionComparitor.cs
  src/KubernetesClient/Versioning/ModelConvertionOperators.cs
  src/KubernetesClient/Versioning/VersionConverter.cs
  src/KubernetesClient/generated/ModelOperators.cs
  src/KubernetesClient/generated/VersionConverter.cs
  tests/KubernetesClient.Tests/VersionConverterTests.cs
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#451 Removed NETSTANDARD2_0 IFDefs and added Brackets
  src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs
  src/KubernetesClient/ModelExtensions.cs
  src/KubernetesClient/generated/VersionConverter.cs
  tests/KubernetesClient.Tests/ModelExtensionTests.cs
Labels: cncf-cla: yes, lgtm, size/L
