Repository kubernetes-client/csharp, pull requests merged in 2020-04, with the labels that each got.

#386 Improve Watcher thread utilisation.
  src/KubernetesClient/KubernetesClient.csproj
  src/KubernetesClient/Watcher.cs
  src/KubernetesClient/WatcherDelegatingHandler.cs
Labels: approved, cncf-cla: yes, lgtm, size/L

#389 Test exception type expected for .NET Standard 2.0
  tests/KubernetesClient.Tests/WatchTests.cs
Labels: cncf-cla: yes, lgtm, size/XS

#379 Create watch handle for http client factory
  examples/httpClientFactory/Program.cs
  src/KubernetesClient/KubernetesClientConfiguration.HttpClientHandler.cs
Labels: approved, cncf-cla: yes, lgtm, size/XS

#395 Upgrade to .NET Core SDK 3.1.
  .github/workflows/dotnet.yaml
  .github/workflows/nuget.yaml
  install-linux.sh
  install-osx.sh
Labels: cncf-cla: yes, size/M

#401 Fix nuget's "Setup SxS dotnet" not being run.
  .github/workflows/nuget.yaml
Labels: cncf-cla: yes, size/XS

#404 Add IKubernetesObject<TMetadata>
  gen/KubernetesWatchGenerator/Program.cs
  src/KubernetesClient/IKubernetesObject.cs
  src/KubernetesClient/generated/ModelExtensions.cs
Labels: approved, cncf-cla: yes, lgtm, size/L

#407 Add gitattributes
  .gitattributes
Labels: approved, cncf-cla: yes, lgtm, size/M

#413 Fix test project namespace inconsistency
  tests/KubernetesClient.Tests/Kubernetes.WebSockets.Tests.cs
  tests/KubernetesClient.Tests/KubernetesClient.Tests.csproj
  tests/KubernetesClient.Tests/Mock/MockWebSocket.cs
  tests/KubernetesClient.Tests/Mock/MockWebSocketBuilder.cs
  tests/KubernetesClient.Tests/StreamDemuxerTests.cs
Labels: approved, cncf-cla: yes, lgtm, size/S

#414 Add WatchEventType.Bookmark
  src/KubernetesClient/Watcher.cs
Labels: approved, cncf-cla: yes, lgtm, size/S

#415 Remove retry
  src/KubernetesClient/Kubernetes.ConfigInit.cs
Labels: approved, cncf-cla: yes, lgtm, size/M

#423 Improve documentation for BuildDefaultConfig
  src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs
Labels: cncf-cla: yes, lgtm, size/XS

#421 Allow testing of internal methods
  src/KubernetesClient/Properties/AssemblyInfo.cs
  tests/KubernetesClient.Tests/KubernetesClient.Tests.csproj
Labels: approved, cncf-cla: yes, lgtm, size/XS

#419 Remove Microsoft.AspNetCore.WebUtilities dependency
  src/KubernetesClient/Kubernetes.Watch.cs
  src/KubernetesClient/Kubernetes.WebSocket.cs
  src/KubernetesClient/KubernetesClient.csproj
  src/KubernetesClient/Utilities.cs
  src/KubernetesClient/WatcherDelegatingHandler.cs
  tests/KubernetesClient.Tests/Kubernetes.WebSockets.Tests.cs
  tests/KubernetesClient.Tests/UtilityTests.cs
Labels: approved, cncf-cla: yes, lgtm, size/L

#424 Override ToString on V1Status
  src/KubernetesClient/ModelExtensions.cs
  tests/KubernetesClient.Tests/ModelExtensionTests.cs
Labels: approved, cncf-cla: yes, lgtm, size/M

#425 Share code to create ServiceClientCredentials
  src/KubernetesClient/Kubernetes.ConfigInit.cs
Labels: approved, cncf-cla: yes, lgtm, size/M

#427 Fix issue with WatchDispose test
  tests/KubernetesClient.Tests/WatchTests.cs
Labels: approved, cncf-cla: yes, lgtm, size/XS

#430 remove travis related files
  .travis.yml
  ci.sh
  install-linux.sh
  install-osx.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#429 fix generator yields wrong file name
  gen/KubernetesWatchGenerator/Program.cs
Labels: approved, cncf-cla: yes, lgtm, size/XS

#431 Add in formatting pre-check.
  .github/workflows/dotnet.yaml
  examples/attach/Attach.cs
  examples/exec/Exec.cs
  examples/logs/Logs.cs
  examples/namespace/Namespace.cs
  gen/KubernetesWatchGenerator/Program.cs
  src/KubernetesClient/CertUtils.cs
  src/KubernetesClient/IItems.cs
  src/KubernetesClient/IMetadata.cs
  src/KubernetesClient/ISpec.cs
  src/KubernetesClient/IStatus.cs
  src/KubernetesClient/IValidate.cs
  src/KubernetesClient/IntstrIntOrString.cs
  src/KubernetesClient/KubeConfigModels/AuthProvider.cs
  src/KubernetesClient/KubeConfigModels/ClusterEndpoint.cs
  src/KubernetesClient/KubeConfigModels/K8SConfiguration.cs
  src/KubernetesClient/Kubernetes.ConfigInit.cs
  src/KubernetesClient/Kubernetes.Exec.cs
  src/KubernetesClient/Kubernetes.Watch.cs
  src/KubernetesClient/Kubernetes.WebSocket.cs
  src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs
  src/KubernetesClient/KubernetesClientConfiguration.HttpClientHandler.cs
  src/KubernetesClient/KubernetesClientConfiguration.InCluster.cs
  src/KubernetesClient/ResourceQuantity.cs
  src/KubernetesClient/V1Patch.cs
  src/KubernetesClient/Watcher.cs
  src/KubernetesClient/WatcherDelegatingHandler.cs
  src/KubernetesClient/Yaml.cs
  tests/KubernetesClient.Tests/AuthTests.cs
  tests/KubernetesClient.Tests/TaskAssert.cs
  tests/KubernetesClient.Tests/V1StatusObjectViewTests.cs
  tests/KubernetesClient.Tests/YamlTests.cs
Labels: approved, cncf-cla: yes, lgtm, size/L

#428 Stylecop
  Directory.Build.props
  Directory.Build.targets
  gen/KubernetesWatchGenerator/IKubernetes.Watch.cs.template
  gen/KubernetesWatchGenerator/Kubernetes.Watch.cs.template
  gen/KubernetesWatchGenerator/ModelExtensions.cs.template
  kubernetes-client.ruleset
  src/KubernetesClient/generated/IKubernetes.Watch.cs
  src/KubernetesClient/generated/Kubernetes.Watch.cs
  src/KubernetesClient/generated/ModelExtensions.cs
  stylecop.json
  tests/KubernetesClient.Tests/Logging/TestOutputLogger.cs
  tests/KubernetesClient.Tests/Logging/TestOutputLoggerProvider.cs
Labels: approved, cncf-cla: yes, lgtm, size/M

#411 Allow KUBECONFIG environment variable to point to multiple files
  src/KubernetesClient/KubeConfigModels/K8SConfiguration.cs
  src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs
  tests/KubernetesClient.Tests/KubernetesClientConfigurationTests.cs
  tests/KubernetesClient.Tests/assets/kubeconfig.preferences-extensions.yml
  tests/KubernetesClient.Tests/assets/kubeconfig.user-pass.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#402 Allow token refresh for GCP
  src/KubernetesClient/Authentication/GcpTokenProvider.cs
  src/KubernetesClient/Kubernetes.ConfigInit.cs
  src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs
  src/KubernetesClient/KubernetesClientConfiguration.cs
  tests/KubernetesClient.Tests/GcpTokenProviderTests.cs
  tests/KubernetesClient.Tests/OperatingSystem.cs
  tests/KubernetesClient.Tests/OperatingSystemFact.cs
  tests/KubernetesClient.Tests/assets/gcloud-config-helper.json
  tests/KubernetesClient.Tests/assets/mock-gcloud.cmd
  tests/KubernetesClient.Tests/assets/mock-gcloud.sh
Labels: approved, cncf-cla: yes, lgtm, size/L
