Repository kubernetes-client/csharp, pull requests merged in 2020-11, with the labels that each got.

#512 Style fix1
  examples/logs/Logs.cs
  kubernetes-client.ruleset
  src/KubernetesClient/Authentication/TokenFileAuth.cs
  src/KubernetesClient/ByteBuffer.cs
  src/KubernetesClient/CertUtils.cs
  src/KubernetesClient/Exceptions/KubeConfigException.cs
  src/KubernetesClient/Exceptions/KubernetesClientException.cs
  src/KubernetesClient/Extensions.cs
  src/KubernetesClient/IntstrIntOrString.cs
  src/KubernetesClient/KubeConfigModels/AuthProvider.cs
  src/KubernetesClient/KubeConfigModels/Cluster.cs
  src/KubernetesClient/KubeConfigModels/ClusterEndpoint.cs
  src/KubernetesClient/KubeConfigModels/Context.cs
  src/KubernetesClient/KubeConfigModels/ContextDetails.cs
  src/KubernetesClient/KubeConfigModels/ExecCredentialResponse.cs
  src/KubernetesClient/KubeConfigModels/ExternalExecution.cs
  src/KubernetesClient/KubeConfigModels/K8SConfiguration.cs
  src/KubernetesClient/KubeConfigModels/User.cs
  src/KubernetesClient/KubeConfigModels/UserCredentials.cs
  src/KubernetesClient/Kubernetes.ConfigInit.cs
  src/KubernetesClient/Kubernetes.Exec.cs
  src/KubernetesClient/Kubernetes.Watch.cs
  src/KubernetesClient/Kubernetes.WebSocket.cs
  src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs
  src/KubernetesClient/KubernetesList.cs
  src/KubernetesClient/ModelExtensions.cs
  src/KubernetesClient/StreamType.cs
  src/KubernetesClient/StringQuotingEmitter.cs
  src/KubernetesClient/V1Patch.cs
  src/KubernetesClient/Versioning/KubernetesVersionComparer.cs
  src/KubernetesClient/Versioning/VersionConverter.cs
  src/KubernetesClient/Watcher.cs
  src/KubernetesClient/WatcherDelegatingHandler.cs
  src/KubernetesClient/WatcherExt.cs
  src/KubernetesClient/WebSocketBuilder.cs
  src/KubernetesClient/Yaml.cs
  src/KubernetesClient/generated/VersionConverter.cs
  tests/KubernetesClient.Tests/AuthTests.cs
  tests/KubernetesClient.Tests/ByteBufferTests.cs
  tests/KubernetesClient.Tests/CertUtilsTests.cs
  tests/KubernetesClient.Tests/CertificateValidationTests.cs
  tests/KubernetesClient.Tests/GcpTokenProviderTests.cs
  tests/KubernetesClient.Tests/KubernetesClientConfigurationTests.cs
  tests/KubernetesClient.Tests/Logging/TestOutputLogger.cs
  tests/KubernetesClient.Tests/Mock/MockWebSocket.cs
  tests/KubernetesClient.Tests/Mock/Server/Controllers/PodExecController.cs
  tests/KubernetesClient.Tests/Mock/Server/Controllers/PodPortForwardController.cs
  tests/KubernetesClient.Tests/PodExecTests.cs
  tests/KubernetesClient.Tests/StreamDemuxerTests.cs
  tests/KubernetesClient.Tests/TaskAssert.cs
  tests/KubernetesClient.Tests/TokenFileAuthTests.cs
  tests/KubernetesClient.Tests/VersionConverterTests.cs
  tests/KubernetesClient.Tests/WatchTests.cs
  tests/KubernetesClient.Tests/WebSocketTestBase.cs
  tests/KubernetesClient.Tests/YamlTests.cs
Labels: approved, cncf-cla: yes, lgtm, size/L

#513 E2E test with minikube on gh action
  .github/workflows/buildtest.yaml
  Directory.Build.targets
  kubernetes-client.sln
  tests/E2E.Tests/E2E.Tests.csproj
  tests/E2E.Tests/MinikubeFactAttribute.cs
  tests/E2E.Tests/MnikubeTests.cs
  tests/SkipTestLogger/SkipTestLogger.cs
  tests/SkipTestLogger/SkipTestLogger.csproj
Labels: approved, cncf-cla: yes, lgtm, size/L

#520 small external auth fix
  src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs
Labels: approved, cncf-cla: yes, lgtm, size/XS

#517 fix patch example.
  examples/patch/Program.cs
  src/KubernetesClient/V1Patch.cs
  src/KubernetesClient/V1PathJsonConverter.cs
Labels: approved, cncf-cla: yes, lgtm, size/M

#522 Add missing net5 in packing
  .github/workflows/nuget.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#519 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
  global.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#525 Add an initial generic client.
  examples/generic/Generic.cs
  examples/generic/generic.csproj
  src/KubernetesClient/GenericClient.cs
Labels: approved, cncf-cla: yes, lgtm, size/L

#530 add V1Patch for patch custom obj
  src/KubernetesClient/Kubernetes.Header.cs
Labels: approved, cncf-cla: yes, lgtm, size/XS

#526 move integration test to minikube proj
  tests/E2E.Tests/E2E.Tests.csproj
  tests/E2E.Tests/MnikubeTests.cs
  tests/KubernetesClient.Tests/WatchTests.cs
Labels: approved, cncf-cla: yes, lgtm, size/L
