Repository kubernetes-client/csharp, pull requests merged in 2020-03, with the labels that each got.

#359 Out-of-tree client authentication providers (UserCredentials exec option) for asp.net core applications
  src/KubernetesClient/KubeConfigModels/ExecCredentialResponse.cs
  src/KubernetesClient/KubeConfigModels/ExternalExecution.cs
  src/KubernetesClient/KubeConfigModels/UserCredentials.cs
  src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs
  tests/KubernetesClient.Tests/AuthTests.cs
Labels: approved, cncf-cla: yes, lgtm, size/L

#361 [breaking changes] cleanup targets
  ci.sh
  gen/KubernetesWatchGenerator/KubernetesWatchGenerator.csproj
  src/KubernetesClient/Kubernetes.ConfigInit.cs
  src/KubernetesClient/KubernetesClient.csproj
  src/KubernetesClient/KubernetesClientConfiguration.HttpClientHandler.cs
  src/KubernetesClient/KubernetesException.cs
  tests/KubernetesClient.Tests/KubernetesClient.Tests.csproj
  tests/KubernetesClient.Tests/Mock/MockKubeApiServer.cs
  tests/KubernetesClient.Tests/YamlTests.cs
Labels: approved, cncf-cla: yes, lgtm, size/M

#365 fix DisposeWatch test fickle
  tests/KubernetesClient.Tests/WatchTests.cs
Labels: approved, cncf-cla: yes, lgtm, size/XS

#366 revert move fraction internal
  src/KubernetesClient/Fractions/Extensions/MathExt.cs
  src/KubernetesClient/Fractions/Formatter/DefaultFractionFormatProvider.cs
  src/KubernetesClient/Fractions/Formatter/DefaultFractionFormatter.cs
  src/KubernetesClient/Fractions/Fraction.CompareTo.cs
  src/KubernetesClient/Fractions/Fraction.Constructors.cs
  src/KubernetesClient/Fractions/Fraction.ConvertFrom.cs
  src/KubernetesClient/Fractions/Fraction.ConvertTo.cs
  src/KubernetesClient/Fractions/Fraction.Equality.cs
  src/KubernetesClient/Fractions/Fraction.Math.cs
  src/KubernetesClient/Fractions/Fraction.Operators.cs
  src/KubernetesClient/Fractions/Fraction.ToString.cs
  src/KubernetesClient/Fractions/Fraction.cs
  src/KubernetesClient/Fractions/FractionState.cs
  src/KubernetesClient/Fractions/InvalidNumberException.cs
  src/KubernetesClient/Fractions/README.md
  src/KubernetesClient/Fractions/TypeConverters/FractionTypeConverter.cs
  src/KubernetesClient/Fractions/license.txt
  src/KubernetesClient/KubernetesClient.csproj
  src/KubernetesClient/ResourceQuantity.cs
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#367 following up after switching to gh action
  .azure-pipelines.yaml
  .github/workflows/dotnet.yaml
  .github/workflows/nuget.yaml
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#373 Use value from ContextDetails to populate Namespace
  src/KubernetesClient/KubeConfigModels/Context.cs
  src/KubernetesClient/KubeConfigModels/ContextDetails.cs
  src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs
  tests/KubernetesClient.Tests/KubernetesClientConfigurationTests.cs
  tests/KubernetesClient.Tests/assets/kubeconfig.no-context-details.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#369 fix watch generator uses different name pattern from gen project
  gen/KubernetesWatchGenerator/Program.cs
  src/KubernetesClient/generated/IKubernetes.Watch.cs
  src/KubernetesClient/generated/Kubernetes.Watch.cs
  src/KubernetesClient/generated/ModelExtensions.cs
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#370 Ensure that awaits do not continue on the captured context.
  src/KubernetesClient/Kubernetes.WebSocket.cs
  src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs
  src/KubernetesClient/StreamDemuxer.cs
  src/KubernetesClient/Watcher.cs
  src/KubernetesClient/WatcherDelegatingHandler.cs
  src/KubernetesClient/Yaml.cs
  tests/KubernetesClient.Tests/KubernetesClient.Tests.csproj
  tests/KubernetesClient.Tests/KubernetesClientConfigurationTests.cs
Labels: approved, cncf-cla: yes, lgtm, size/M

#376 fix watch=true doesn't respect cancellation token
  src/KubernetesClient/WatcherDelegatingHandler.cs
  tests/KubernetesClient.Tests/WatchTests.cs
Labels: approved, cncf-cla: yes, lgtm, size/L

#377 update source link to release
  src/KubernetesClient/KubernetesClient.csproj
Labels: approved, cncf-cla: yes, lgtm, size/XS

#378 Add interfaces for generated Kubernetes objects
  .gitignore
  gen/KubernetesWatchGenerator/ModelExtensions.cs.template
  gen/KubernetesWatchGenerator/Program.cs
  src/KubernetesClient/IItems.cs
  src/KubernetesClient/IMetadata.cs
  src/KubernetesClient/ISpec.cs
  src/KubernetesClient/IStatus.cs
  src/KubernetesClient/IValidate.cs
  src/KubernetesClient/KubernetesEntityAttribute.cs
  src/KubernetesClient/KubernetesList.cs
  src/KubernetesClient/generated/ModelExtensions.cs
Labels: approved, cncf-cla: yes, lgtm, size/XL

#384 Remove dupe null check
  src/KubernetesClient/Kubernetes.WebSocket.cs
Labels: cncf-cla: yes, size/XS
