Repository kubernetes-client/csharp, pull requests merged in 2021-04, with the labels that each got.

#596 fix partial chain
  src/KubernetesClient/Kubernetes.ConfigInit.cs
Labels: approved, cncf-cla: yes, lgtm, size/XS

#599 Default type map for YAML deserialization
  src/KubernetesClient/Yaml.cs
  tests/KubernetesClient.Tests/YamlTests.cs
Labels: approved, cncf-cla: yes, lgtm, size/L

#601 fix github action build
  nuget.config
Labels: approved, cncf-cla: yes, lgtm, size/XS

#602 documentation syntaxt issues resolved
  src/KubernetesClient/ExecAsyncCallback.cs
  src/KubernetesClient/GenericClient.cs
  src/KubernetesClient/IKubernetesObject.cs
Labels: cncf-cla: yes, lgtm, size/S

#591 Add a Prometheus handler.
  README.md
  examples/prometheus/Prometheus.cs
  examples/prometheus/prometheus.csproj
  src/KubernetesClient/KubernetesClient.csproj
  src/KubernetesClient/KubernetesRequestDigest.cs
  src/KubernetesClient/PrometheusHandler.cs
Labels: approved, cncf-cla: yes, lgtm, size/L

#608 Trimming double quote from parsed KUBECONFIG path.
  src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs
Labels: approved, cncf-cla: yes, lgtm, size/XS

#604 Update LICENSE
  LICENSE
Labels: approved, cncf-cla: yes, lgtm, size/XS
