Repository kubernetes-client/csharp, pull requests merged in 2021-02, with the labels that each got.

#549 Make LineSeparatedHttpContent public
  src/KubernetesClient/WatcherDelegatingHandler.cs
Labels: approved, cncf-cla: yes, lgtm, size/XS

#561 remove always false
  .github/workflows/buildtest.yaml
  src/KubernetesClient/Authentication/OidcTokenProvider.cs
Labels: approved, cncf-cla: yes, lgtm, size/XS

#565 Fix typos
  src/KubernetesClient/KubeConfigModels/UserCredentials.cs
Labels: cncf-cla: yes, size/XS

#571 fix file not closed
  src/KubernetesClient/Yaml.cs
Labels: approved, cncf-cla: yes, lgtm, size/XS

#573 Fix ObjectDisposedException thrown when calling LoadAllFromFileAsync
  src/KubernetesClient/Yaml.cs
  tests/KubernetesClient.Tests/YamlTests.cs
Labels: cncf-cla: yes, lgtm, size/M
