Repository kubernetes-client/csharp, pull requests merged in 2021-05, with the labels that each got.

#620 Adding new properties in ExternalExecution model.
  src/KubernetesClient/KubeConfigModels/ExternalExecution.cs
Labels: approved, cncf-cla: yes, lgtm, size/S

#626 nuget package/CI improvement
  .github/workflows/nuget.yaml
  src/KubernetesClient/KubernetesClient.csproj
Labels: cncf-cla: yes, lgtm, size/M

#635 Expose kube config default location
  src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs
Labels: approved, cncf-cla: yes, lgtm, size/XS

#631 Update TokenFileAuth
  src/KubernetesClient/Authentication/TokenFileAuth.cs
Labels: approved, cncf-cla: yes, lgtm, size/S

#633 fix: oidc
  src/KubernetesClient/Authentication/OidcTokenProvider.cs
  src/KubernetesClient/KubernetesClient.csproj
  tests/KubernetesClient.Tests/AuthTests.cs
  tests/KubernetesClient.Tests/KubernetesClientConfigurationTests.cs
  tests/KubernetesClient.Tests/OidcAuthTests.cs
  tests/KubernetesClient.Tests/TokenFileAuthTests.cs
  tests/KubernetesClient.Tests/assets/kubeconfig.user-oidc.yml
Labels: approved, cncf-cla: yes, lgtm, size/L
