Repository kubernetes-client/csharp, pull requests merged in 2021-09, with the labels that each got.

#696 add implicit cast back
  src/KubernetesClient/ResourceQuantity.cs
Labels: size/XS, cncf-cla: yes, lgtm, approved

#586 expose IAsyncEnumerable API for watcher
  src/KubernetesClient/KubernetesClient.csproj
  src/KubernetesClient/Watcher.cs
  src/KubernetesClient/WatcherExt.cs
  tests/KubernetesClient.Tests/WatchTests.cs
Labels: cncf-cla: yes, size/L, lgtm, approved

#702 Upgrade Microsoft.Rest.ClientRuntime from 2.3.10 to 2.3.23
  src/KubernetesClient/KubernetesClient.csproj
  tests/KubernetesClient.Tests/PodExecTests.cs
Labels: cncf-cla: yes, size/S

#716 add version matrix
  README.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#715 add async foreach example
  examples/watch/Program.cs
  src/KubernetesClient/WatcherExt.cs
Labels: cncf-cla: yes, size/S, lgtm, approved
