Repository kubernetes-client/csharp, pull requests merged in 2021-11, with the labels that each got.

#682 Ported GenericKubernetesApi from java along with other utilities
  examples/GenericKubernetesApi/GenericKubernetesApi.csproj
  examples/GenericKubernetesApi/Program.cs
  kubernetes-client.sln
  src/KubernetesClient/Util/Common/BadNotificationException.cs
  src/KubernetesClient/Util/Common/Config.cs
  src/KubernetesClient/Util/Common/Generic/GenericKubernetesApi.cs
  src/KubernetesClient/Util/Common/Generic/KubernetesApiResponse.cs
  src/KubernetesClient/Util/Common/Generic/Options/CreateOptions.cs
  src/KubernetesClient/Util/Common/Generic/Options/GetOptions.cs
  src/KubernetesClient/Util/Common/Generic/Options/ListOptions.cs
  src/KubernetesClient/Util/Common/Generic/Options/PatchOptions.cs
  src/KubernetesClient/Util/Common/Generic/Options/UpdateOptions.cs
  src/KubernetesClient/Util/Common/Namespaces.cs
  src/KubernetesClient/Util/Informer/Cache/Cache.cs
  src/KubernetesClient/Util/Informer/Cache/IStore.cs
  tests/KubernetesClient.Tests/Util/Common/Generic/GenericKubernetesApiTest.cs
  tests/KubernetesClient.Tests/Util/Helpers.cs
  tests/KubernetesClient.Tests/Util/Informer/Cache/CacheTest.cs
  tests/KubernetesClient.Tests/Util/Informer/Cache/CachesTest.cs
  tests/KubernetesClient.Tests/Util/Informer/Cache/ListerTest.cs
  tests/KubernetesClient.Tests/Util/Informer/Cache/ReflectorTest.cs
  tests/KubernetesClient.Tests/Util/Informer/Cache/Util.cs
  tests/KubernetesClient.Tests/Util/MockKubeApiServerOptions.cs
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#744 add generic create
  examples/generic/Generic.cs
  kubernetes-client.sln
  src/KubernetesClient/GenericClient.cs
  tests/E2E.Tests/MnikubeTests.cs
Labels: cncf-cla: yes, size/L, lgtm, approved

#745 add net6 targets
  .github/workflows/buildtest.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/nuget.yaml
  src/KubernetesClient/KubernetesClient.csproj
  tests/E2E.Tests/E2E.Tests.csproj
  tests/KubernetesClient.Tests/KubernetesClient.Tests.csproj
Labels: cncf-cla: yes, size/M, lgtm, approved
