Repository kubernetes-client/csharp, pull requests merged in 2021-03, with the labels that each got.

#574 Support IgnoreUnmatchedProperties in YAML serialization
  src/KubernetesClient/Yaml.cs
  tests/KubernetesClient.Tests/KubernetesClientConfigurationTests.cs
  tests/KubernetesClient.Tests/YamlTests.cs
  tests/KubernetesClient.Tests/assets/kubeconfig.additional-properties.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#579 add apply patch type
  src/KubernetesClient/Kubernetes.Header.cs
  src/KubernetesClient/V1Patch.cs
Labels: approved, cncf-cla: yes, lgtm, size/XS

#580 fix typo V1PathJsonConverter -> V1PatchJsonConverter
  src/KubernetesClient/V1Patch.cs
  src/KubernetesClient/V1PatchJsonConverter.cs
Labels: approved, cncf-cla: yes, lgtm, size/XS

#588 better tcpkeepalive on linux
  src/KubernetesClient/Kubernetes.ConfigInit.cs
  src/KubernetesClient/KubernetesClientConfiguration.cs
Labels: approved, cncf-cla: yes, lgtm, size/M

#592 force http2 in handler
  src/KubernetesClient/WatcherDelegatingHandler.cs
Labels: approved, cncf-cla: yes, lgtm, size/XS
