Repository kubernetes-client/csharp, pull requests merged in 2021-08, with the labels that each got.

#665 Initial port of cache functions from java client
  src/KubernetesClient/KubernetesClient.csproj
  src/KubernetesClient/Util/Common/CallGeneratorParams.cs
  src/KubernetesClient/Util/Common/CollectionsExtensions.cs
  src/KubernetesClient/Util/Informer/Cache/Cache.cs
  src/KubernetesClient/Util/Informer/Cache/Caches.cs
  src/KubernetesClient/Util/Informer/Cache/DeletedFinalStateUnknown.cs
  src/KubernetesClient/Util/Informer/Cache/DeltaType.cs
  src/KubernetesClient/Util/Informer/Cache/IIndexer.cs
  src/KubernetesClient/Util/Informer/Cache/IStore.cs
  src/KubernetesClient/Util/Informer/Cache/Lister.cs
  src/KubernetesClient/Util/Informer/Cache/MutablePair.cs
  tests/KubernetesClient.Tests/KubernetesClient.Tests.csproj
  tests/KubernetesClient.Tests/Util/Informer/Cache/CacheTest.cs
  tests/KubernetesClient.Tests/Util/Informer/Cache/CachesTest.cs
  tests/KubernetesClient.Tests/Util/Informer/Cache/ListerTest.cs
  tests/KubernetesClient.Tests/Util/Informer/Cache/ReflectorTest.cs
  tests/KubernetesClient.Tests/Util/Informer/Cache/Util.cs
  util/src/KubernetesClient.Util/KubernetesClient.Util.csproj
  util/src/KubernetesClient.Util/KubernetesClient.Util.csproj.DotSettings
  util/tests/KubernetesClient.Util.Tests/KubernetesClient.Util.Tests.csproj
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#674 Fix typos
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#676 fix flaky leader election tests
  tests/KubernetesClient.Tests/LeaderElection/LeaderElectionTests.cs
Labels: cncf-cla: yes, size/M, lgtm, approved

#669 port autorest2 template to local generate tools
  gen/KubernetesGenerator/IKubernetes.Watch.cs.template
  gen/KubernetesGenerator/IKubernetes.cs.template
  gen/KubernetesGenerator/Kubernetes.Watch.cs.template
  gen/KubernetesGenerator/Kubernetes.cs.template
  gen/KubernetesGenerator/KubernetesExtensions.cs.template
  gen/KubernetesGenerator/KubernetesGenerator.csproj
  gen/KubernetesGenerator/Model.cs.template
  gen/KubernetesGenerator/ModelExtensions.cs.template
  gen/KubernetesGenerator/ModelOperators.cs.template
  gen/KubernetesGenerator/Program.cs
  gen/KubernetesGenerator/VersionConverter.cs.template
  gen/KubernetesWatchGenerator/KubernetesWatchGenerator.csproj
  kubernetes-client.sln
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#678 fix build warning
  src/KubernetesClient/FileUtils.cs
Labels: size/XS, cncf-cla: yes, lgtm, approved
