Repository kubernetes-client/csharp, pull requests merged in 2021-01, with the labels that each got.

#543 fix delay
  src/KubernetesClient/LeaderElection/LeaderElector.cs
  tests/KubernetesClient.Tests/LeaderElection/LeaderElectionTests.cs
Labels: approved, cncf-cla: yes, lgtm, size/S

#544 OIDC support
  kubernetes-client.ruleset
  src/KubernetesClient/Authentication/OidcTokenProvider.cs
  src/KubernetesClient/KubernetesClient.csproj
  src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs
Labels: approved, cncf-cla: yes, lgtm, size/L

#548 Add HttpClient property to the IKubernetes interface
  src/KubernetesClient/IKubernetes.HttpClient.cs
Labels: approved, cncf-cla: yes, lgtm, size/S

#553 KubernetesException: Add an constructor overload which takes a V1Status and an inner exception.
  src/KubernetesClient/Kubernetes.Exec.cs
  src/KubernetesClient/KubernetesException.cs
Labels: approved, cncf-cla: yes, lgtm, size/S

#556 Fix kubeconfig extension handling
  src/KubernetesClient/KubeConfigModels/ClusterEndpoint.cs
  src/KubernetesClient/KubeConfigModels/Context.cs
  src/KubernetesClient/KubeConfigModels/ContextDetails.cs
  src/KubernetesClient/KubeConfigModels/K8SConfiguration.cs
  src/KubernetesClient/KubeConfigModels/NamedExtension.cs
  src/KubernetesClient/KubeConfigModels/UserCredentials.cs
  src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs
  tests/KubernetesClient.Tests/KubernetesClientConfigurationTests.cs
  tests/KubernetesClient.Tests/assets/kubeconfig.cluster-extensions.yml
  tests/KubernetesClient.Tests/assets/kubeconfig.preferences-extensions.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#550 Support wildcard IPv4 and IPv6 addresses
  src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs
  tests/KubernetesClient.Tests/KubernetesClientConfigurationTests.cs
  tests/KubernetesClient.Tests/assets/kubeconfig.wildcard-ipv4.yml
  tests/KubernetesClient.Tests/assets/kubeconfig.wildcard-ipv6.yml
  tests/KubernetesClient.Tests/assets/kubeconfig.wildcard-ipv6_2.yml
Labels: cncf-cla: yes, size/L
