Repository kubernetes-client/csharp, pull requests merged in 2022-04, with the labels that each got.

#816 chore : csr approval example using json patch net package
  examples/csrApproval/Program.cs
  examples/csrApproval/csrApproval.csproj
  kubernetes-client.sln
Labels: cncf-cla: yes, size/L, lgtm

#817 support gh nuget
  .github/workflows/nuget.yaml
Labels: size/XS, cncf-cla: yes, lgtm, approved

#819 Restart sts daemonset deployment example
  examples/restart/Program.cs
  examples/restart/restart.csproj
  kubernetes-client.sln
Labels: cncf-cla: yes, size/L, lgtm, approved

#825 skip dup when push
  .github/workflows/nuget.yaml
Labels: size/XS, cncf-cla: yes, lgtm, approved

#827 +tg123, move krabhishek8260 to emeritus
  OWNERS
Labels: size/XS, cncf-cla: yes, lgtm, approved

#830 init kubectl
  kubernetes-client.sln
  src/KubernetesClient.Basic/GeneratedApiVersion.cs
  src/KubernetesClient.Basic/KubernetesClient.Basic.csproj
  src/KubernetesClient.Kubectl/Beta/AsyncKubectl.Version.cs
  src/KubernetesClient.Kubectl/Beta/AsyncKubectl.cs
  src/KubernetesClient.Kubectl/Beta/Kubectl.Version.cs
  src/KubernetesClient.Kubectl/Beta/Kubectl.cs
  src/KubernetesClient.Kubectl/KubernetesClient.Kubectl.csproj
  src/KubernetesClient.Models/GeneratedModelVersion.cs
  src/KubernetesClient.Models/KubernetesClient.Models.csproj
  src/LibKubernetesGenerator/KubernetesClientSourceGenerator.cs
  src/LibKubernetesGenerator/VersionGenerator.cs
  tests/E2E.Tests/MinikubeTests.cs
  tests/Kubectl.Tests/Kubectl.Tests.csproj
  tests/Kubectl.Tests/KubectlTests.Version.cs
  tests/Kubectl.Tests/KubectlTests.cs
Labels: cncf-cla: yes, size/L, lgtm, approved

#832 some static optimization
  src/KubernetesClient.Basic/AbstractKubernetes.cs
  src/KubernetesClient/Kubernetes.cs
  src/LibKubernetesGenerator/UtilHelper.cs
  src/LibKubernetesGenerator/templates/IKubernetes.cs.template
  src/LibKubernetesGenerator/templates/Kubernetes.cs.template
  src/LibKubernetesGenerator/templates/KubernetesExtensions.cs.template
  src/LibKubernetesGenerator/templates/Model.cs.template
  src/LibKubernetesGenerator/templates/ModelExtensions.cs.template
Labels: cncf-cla: yes, size/M, lgtm, approved

#833 Set http 2.0 for .net 5.0+
  src/KubernetesClient/Kubernetes.cs
Labels: size/XS, cncf-cla: yes, lgtm, approved

#834 fix conditional compilation for net 5.0+
  src/KubernetesClient/Authentication/TokenFileAuth.cs
Labels: size/XS, cncf-cla: yes, lgtm, approved

#835 Fix json deserialize error when watch without any result
  src/KubernetesClient/LineSeparatedHttpContent.cs
Labels: size/XS, cncf-cla: yes, lgtm, approved

#837 Allow configurable Http KeepAlive parameters
  src/KubernetesClient/Kubernetes.ConfigInit.cs
  src/KubernetesClient/KubernetesClientConfiguration.cs
Labels: cncf-cla: yes, size/S, lgtm, approved

#836 testcase to check http2 set
  tests/KubernetesClient.Tests/WatchTests.cs
Labels: cncf-cla: yes, size/M, lgtm, approved

#844 Update exception message in KubernetesClientConfiguration.InCluster.cs
  src/KubernetesClient/KubernetesClientConfiguration.InCluster.cs
Labels: size/XS, cncf-cla: yes, lgtm, approved
