Repository kubernetes-client/csharp, pull requests merged in 2022-02, with the labels that each got.

#766 Add environment variable checking for in cluster configs.
  src/KubernetesClient/KubernetesClientConfiguration.InCluster.cs
  tests/KubernetesClient.Tests/KubernetesClientConfigurationTests.cs
Labels: cncf-cla: yes, size/M, lgtm, approved

#777 Support .net 6 for tcp keep alive
  src/KubernetesClient/Kubernetes.ConfigInit.cs
  src/KubernetesClient/Kubernetes.WebSocket.cs
Labels: size/XS, cncf-cla: yes, lgtm

#780 fix codeql
  .github/workflows/codeql-analysis.yml
Labels: cncf-cla: yes, size/L, lgtm, approved

#781 Add http2 keep alive in watch
  src/KubernetesClient/Kubernetes.ConfigInit.cs
Labels: size/XS, cncf-cla: yes

#782 fix flaky logger
  .github/workflows/buildtest.yaml
  src/KubernetesClient/KubernetesClient.csproj
  tests/KubernetesClient.Tests/Logging/TestOutputLogger.cs
Labels: cncf-cla: yes, size/S, lgtm, approved

#784 new release strategy
  .github/workflows/draft.yaml
  .github/workflows/nuget.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved

#783 update swagger gen readme
  README.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#785 7.1 remove old autorest
  examples/attach/Attach.cs
  examples/customResource/Program.cs
  examples/httpClientFactory/PodListHostedService.cs
  examples/httpClientFactory/Program.cs
  examples/httpClientFactory/httpClientFactory.csproj
  examples/namespace/NamespaceExample.cs
  examples/watch/Program.cs
  gen/LibKubernetesGenerator/LibKubernetesGenerator.csproj
  gen/LibKubernetesGenerator/templates/IKubernetes.cs.template
  gen/LibKubernetesGenerator/templates/Kubernetes.cs.template
  kubernetes-client.sln
  src/KubernetesClient/Authentication/ExecTokenProvider.cs
  src/KubernetesClient/Authentication/GcpTokenProvider.cs
  src/KubernetesClient/Authentication/OidcTokenProvider.cs
  src/KubernetesClient/Authentication/TokenFileAuth.cs
  src/KubernetesClient/Autorest/BasicAuthenticationCredentials.cs
  src/KubernetesClient/Autorest/HttpExtensions.cs
  src/KubernetesClient/Autorest/HttpMessageWrapper.cs
  src/KubernetesClient/Autorest/HttpOperationException.cs
  src/KubernetesClient/Autorest/HttpOperationResponse.cs
  src/KubernetesClient/Autorest/HttpRequestMessageWrapper.cs
  src/KubernetesClient/Autorest/HttpResponseMessageWrapper.cs
  src/KubernetesClient/Autorest/ITokenProvider.cs
  src/KubernetesClient/Autorest/RestException.cs
  src/KubernetesClient/Autorest/ServiceClientCredentials.cs
  src/KubernetesClient/Autorest/StringTokenProvider.cs
  src/KubernetesClient/Autorest/TokenCredentials.cs
  src/KubernetesClient/IKubernetes.HttpClient.cs
  src/KubernetesClient/IKubernetes.cs
  src/KubernetesClient/KubeConfigModels/ExecCredentialResponse.cs
  src/KubernetesClient/Kubernetes.ConfigInit.cs
  src/KubernetesClient/Kubernetes.Exec.cs
  src/KubernetesClient/Kubernetes.WebSocket.cs
  src/KubernetesClient/Kubernetes.cs
  src/KubernetesClient/KubernetesClient.csproj
  src/KubernetesClient/KubernetesClientConfiguration.HttpClientHandler.cs
  src/KubernetesClient/KubernetesClientConfiguration.cs
  src/KubernetesClient/KubernetesList.cs
  src/KubernetesClient/LeaderElection/LeaderElector.cs
  src/KubernetesClient/LeaderElection/ResourceLock/MetaObjectLock.cs
  src/KubernetesClient/Util/Common/Generic/GenericKubernetesApi.cs
  src/KubernetesClient/WatcherExt.cs
  tests/E2E.Tests/MnikubeTests.cs
  tests/KubernetesClient.Tests/AuthTests.cs
  tests/KubernetesClient.Tests/KubernetesExecTests.cs
  tests/KubernetesClient.Tests/PodExecTests.cs
  tests/KubernetesClient.Tests/WebSocketTestBase.cs
  version.json
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#786 fix build warning
  tests/KubernetesClient.Tests/CertUtilsTests.cs
Labels: size/XS, cncf-cla: yes, lgtm, approved

#787 fix Unable to process file command 'env' successfully.
  version.json
Labels: size/XS, cncf-cla: yes, lgtm, approved

#789 Use Task.CompletedTask
  src/KubernetesClient/Autorest/BasicAuthenticationCredentials.cs
  src/KubernetesClient/Autorest/ServiceClientCredentials.cs
Labels: size/XS, cncf-cla: yes, lgtm

#790 HttpExtensions enhancement
  src/KubernetesClient/Autorest/HttpExtensions.cs
Labels: cncf-cla: yes, size/S, lgtm

#791 Update System.Text.Json dependency
  src/KubernetesClient/KubernetesClient.csproj
Labels: size/XS, cncf-cla: yes, lgtm
