Repository kubernetes-client/csharp, pull requests merged in 2022-07, with the labels that each got.

#904 Add dependabot support for GitHub actions dependencies
  .github/dependabot.yml
Labels: cncf-cla: yes, size/S, lgtm, approved

#910 Consolidation of nuget packages version across test projects
  tests/KubernetesClient.Classic.Tests/KubernetesClient.Classic.Tests.csproj
  tests/KubernetesClient.Tests/KubernetesClient.Tests.csproj
Labels: cncf-cla: yes, size/S, lgtm, approved

#925 913 Fix nuget workflow errors
  .github/workflows/nuget.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#947 Provide KubernetesYaml.SerializeAll method
  src/KubernetesClient.Models/KubernetesYaml.cs
  tests/KubernetesClient.Tests/KubernetesYamlTests.cs
Labels: cncf-cla: yes, size/M, lgtm, approved

#950 ASP.NET core web api DI example
  examples/webApiDependencyInjection/Controllers/ExampleDependencyInjectionOnConstructorController.cs
  examples/webApiDependencyInjection/Controllers/ExampleDependencyInjectionOnMethodController.cs
  examples/webApiDependencyInjection/Program.cs
  examples/webApiDependencyInjection/appsettings.Development.json
  examples/webApiDependencyInjection/appsettings.json
  examples/webApiDependencyInjection/webApiDependencyInjection.csproj
  kubernetes-client.sln
Labels: cncf-cla: yes, size/L, lgtm, approved

#957 fix(StringQuotingEmitter): add missing patterns for double quoting
  src/KubernetesClient.Models/StringQuotingEmitter.cs
  tests/KubernetesClient.Tests/KubernetesYamlTests.cs
Labels: cncf-cla: yes, size/L, lgtm, approved

#962 Copy local file to pod using tar
  examples/cp/Cp.cs
  examples/cp/cp.csproj
Labels: cncf-cla: yes, size/L, lgtm, approved
