Repository kubernetes-client/csharp, pull requests merged in 2022-10, with the labels that each got.

#1043 simplify setup dotnet
  .github/workflows/buildtest.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/draft.yaml
  .github/workflows/nuget.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved

#1051 Use consistent net6.0 TargetFramework
  tests/KubernetesClient.Classic.Tests/KubernetesClient.Classic.Tests.csproj
Labels: size/XS, cncf-cla: yes, lgtm, approved

#1047 Provide strict k8s yaml model deserializer
  src/KubernetesClient.Models/KubernetesYaml.cs
  tests/KubernetesClient.Tests/KubernetesClientConfigurationTests.cs
  tests/KubernetesClient.Tests/KubernetesYamlTests.cs
Labels: cncf-cla: yes, size/M, lgtm, approved

#1061 Fix strict yaml parsing
  src/KubernetesClient.Models/KubernetesYaml.cs
  tests/KubernetesClient.Tests/KubernetesYamlTests.cs
Labels: cncf-cla: yes, size/S, lgtm, approved

#1060 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: cncf-cla: yes, size/M, lgtm, approved
