Repository kubernetes-client/csharp, pull requests merged in 2022-05, with the labels that each got.

#848 Update KubernetesClientConfiguration.ConfigFile.cs
  src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs
Labels: size/XS, cncf-cla: yes, lgtm, approved

#851 remove unused file
  integration-tests.sh
Labels: cncf-cla: yes, size/S, lgtm, approved

#852 readme update for 8.0
  README.md
Labels: cncf-cla: yes, size/M, lgtm, approved

#853 use explicitly impl instead of new
  src/KubernetesClient.Basic/AbstractKubernetes.cs
  src/KubernetesClient.Basic/HttpMethods.cs
  src/KubernetesClient.Basic/Operations.cs
  src/KubernetesClient.Basic/QueryBuilder.cs
  src/KubernetesClient/Kubernetes.cs
  src/LibKubernetesGenerator/templates/AbstractKubernetes.cs.template
  src/LibKubernetesGenerator/templates/Operations.cs.template
Labels: cncf-cla: yes, size/L, lgtm, approved

#857 fix : nullable annotations issue
  examples/restart/Program.cs
Labels: cncf-cla: yes, size/S, lgtm, approved

#860 Updated CertificateValidationCallBack to build the CaCert bundle with respect to the rootChain certs to verify that they are correct.
  src/KubernetesClient/Kubernetes.ConfigInit.cs
  tests/KubernetesClient.Tests/CertificateValidationTests.cs
  tests/KubernetesClient.Tests/assets/ca-bundle-correct.crt
  tests/KubernetesClient.Tests/assets/ca-bundle-incorrect.crt
Labels: cncf-cla: yes, size/L, lgtm, approved

#879 fix a typo in examples/customResource
  examples/customResource/README.md
Labels: size/XS, cncf-cla: yes, lgtm, approved
