Repository kubernetes-client/csharp, pull requests merged in 2022-12, with the labels that each got.

#994 Enhance AbstractKubernetes SendRequest extensibility
  src/KubernetesClient.Basic/AbstractKubernetes.cs
  src/KubernetesClient/Kubernetes.cs
  src/LibKubernetesGenerator/templates/Operations.cs.template
Labels: cncf-cla: yes, size/M, lgtm, lifecycle/stale, approved

#1085 add net7 remove net5
  .github/workflows/buildtest.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/draft.yaml
  .github/workflows/nuget.yaml
  Directory.Build.targets
  README.md
  examples/Directory.Build.props
  global.json
  src/KubernetesClient.Basic/KubernetesClient.Basic.csproj
  src/KubernetesClient.Kubectl/KubernetesClient.Kubectl.csproj
  src/KubernetesClient.Models/KubernetesClient.Models.csproj
  src/KubernetesClient.Models/Versioning/VersionConverter.cs
  src/KubernetesClient/Kubernetes.ConfigInit.cs
  src/KubernetesClient/KubernetesClient.csproj
  tests/E2E.Tests/E2E.Tests.csproj
  tests/Kubectl.Tests/Kubectl.Tests.csproj
  tests/KubernetesClient.Classic.Tests/KubernetesClient.Classic.Tests.csproj
  tests/KubernetesClient.Tests/KubernetesClient.Tests.csproj
  version.json
Labels: cncf-cla: yes, size/M, lgtm, approved

#1042 remove unused util code
  src/KubernetesClient.Util/KubernetesClient.Util.csproj
  src/KubernetesClient/KubernetesClient.csproj
  src/KubernetesClient/Util/Common/BadNotificationException.cs
  src/KubernetesClient/Util/Common/CallGeneratorParams.cs
  src/KubernetesClient/Util/Common/CollectionsExtensions.cs
  src/KubernetesClient/Util/Common/Config.cs
  src/KubernetesClient/Util/Common/Generic/GenericKubernetesApi.cs
  src/KubernetesClient/Util/Common/Generic/KubernetesApiResponse.cs
  src/KubernetesClient/Util/Common/Generic/Options/CreateOptions.cs
  src/KubernetesClient/Util/Common/Generic/Options/GetOptions.cs
  src/KubernetesClient/Util/Common/Generic/Options/ListOptions.cs
  src/KubernetesClient/Util/Common/Generic/Options/PatchOptions.cs
  src/KubernetesClient/Util/Common/Generic/Options/UpdateOptions.cs
  src/KubernetesClient/Util/Common/Namespaces.cs
  src/KubernetesClient/Util/Informer/Cache/Cache.cs
  src/KubernetesClient/Util/Informer/Cache/Caches.cs
  src/KubernetesClient/Util/Informer/Cache/DeletedFinalStateUnknown.cs
  src/KubernetesClient/Util/Informer/Cache/DeltaType.cs
  src/KubernetesClient/Util/Informer/Cache/IIndexer.cs
  src/KubernetesClient/Util/Informer/Cache/IStore.cs
  src/KubernetesClient/Util/Informer/Cache/Lister.cs
  src/KubernetesClient/Util/Informer/Cache/MutablePair.cs
  tests/KubernetesClient.Tests/KubernetesClient.Tests.csproj
  tests/KubernetesClient.Tests/Util/Common/Generic/GenericKubernetesApiTest.cs
  tests/KubernetesClient.Tests/Util/Helpers.cs
  tests/KubernetesClient.Tests/Util/Informer/Cache/CacheTest.cs
  tests/KubernetesClient.Tests/Util/Informer/Cache/CachesTest.cs
  tests/KubernetesClient.Tests/Util/Informer/Cache/ListerTest.cs
  tests/KubernetesClient.Tests/Util/MockKubeApiServerOptions.cs
  tests/KubernetesClient.Util.Tests/KubernetesClient.Util.Tests.csproj
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#1120 way to disable http2
  src/KubernetesClient/Kubernetes.ConfigInit.cs
  src/KubernetesClient/Kubernetes.cs
  src/KubernetesClient/KubernetesClientConfiguration.cs
Labels: cncf-cla: yes, size/S, lgtm, approved

#1121 update system abstract io
  src/KubernetesClient.Classic/KubernetesClient.Classic.csproj
  src/KubernetesClient/KubernetesClient.csproj
  tests/KubernetesClient.Classic.Tests/KubernetesClient.Classic.Tests.csproj
  tests/KubernetesClient.Tests/KubernetesClient.Tests.csproj
Labels: size/XS, cncf-cla: yes, lgtm, approved

#1128 dispose cts after call finish
  src/LibKubernetesGenerator/templates/Operations.cs.template
Labels: size/XS, cncf-cla: yes, lgtm, approved
