Repository kubernetes-client/csharp, pull requests merged in 2022-09, with the labels that each got.

#998 Implement IMetadata interface
  examples/customResource/CustomResourceDefinition.cs
  src/KubernetesClient.Models/NodeMetrics.cs
  src/KubernetesClient.Models/NodeMetricsList.cs
  src/KubernetesClient.Models/PodMetrics.cs
  src/KubernetesClient.Models/PodMetricsList.cs
  src/KubernetesClient.Models/V1PodTemplateSpec.cs
Labels: cncf-cla: yes, size/S, lgtm, approved

#1006 Fix README link to XUnit project
  README.md
Labels: size/XS, cncf-cla: yes, lgtm, approved

#1008 Revert "Bump Microsoft.CodeAnalysis.CSharp from 4.2.0 to 4.3.0"
  src/LibKubernetesGenerator/LibKubernetesGenerator.csproj
Labels: size/XS, cncf-cla: yes, lgtm, approved

#1022 Added msbuild build of project in buildtest action
  .github/workflows/buildtest.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#936 Make use of Cert Flags if Set
  src/KubernetesClient/CertUtils.cs
Labels: cncf-cla: yes, size/S, lgtm, approved

#1023 Fix duplication errors in ruleset
  kubernetes-client.ruleset
Labels: size/XS, cncf-cla: yes, lgtm, approved

#1034 Support round-trip CRD (de)serialization
  src/KubernetesClient.Models/FloatEmitter.cs
  src/KubernetesClient.Models/KubernetesYaml.cs
  src/KubernetesClient/CertUtils.cs
  tests/KubernetesClient.Tests/KubernetesYamlTests.cs
Labels: cncf-cla: yes, size/M, lgtm, approved

#1028 Standardization of using order and object initialization
  examples/namespace/NamespaceExample.cs
  examples/yaml/Program.cs
  src/KubernetesClient.Basic/AbstractKubernetes.cs
  src/KubernetesClient.Basic/Autorest/HttpRequestMessageWrapper.cs
  src/KubernetesClient.Basic/Autorest/TokenCredentials.cs
  src/KubernetesClient.Basic/Global.cs
  src/KubernetesClient.Models/Extensions.cs
  src/KubernetesClient.Models/IItems.cs
  src/KubernetesClient.Models/KubeConfigModels/ExecCredentialResponse.cs
  src/KubernetesClient.Models/KubernetesYaml.cs
  src/KubernetesClient.Models/ResourceQuantity.cs
  src/KubernetesClient.Models/Versioning/VersionConverter.cs
  src/KubernetesClient/Authentication/ExecTokenProvider.cs
  src/KubernetesClient/Authentication/GcpTokenProvider.cs
  src/KubernetesClient/Authentication/OidcTokenProvider.cs
  src/KubernetesClient/Authentication/TokenFileAuth.cs
  src/KubernetesClient/CertUtils.cs
  src/KubernetesClient/Kubernetes.ConfigInit.cs
  src/KubernetesClient/Kubernetes.Exec.cs
  src/KubernetesClient/Kubernetes.WebSocket.cs
  src/KubernetesClient/Kubernetes.cs
  src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs
  src/KubernetesClient/KubernetesClientConfiguration.InCluster.cs
  src/KubernetesClient/KubernetesClientConfiguration.cs
  src/KubernetesClient/KubernetesRequestDigest.cs
  src/KubernetesClient/LeaderElection/LeaderElectionRecord.cs
  src/KubernetesClient/LeaderElection/LeaderElector.cs
  src/KubernetesClient/LeaderElection/ResourceLock/MetaObjectLock.cs
  src/KubernetesClient/LeaderElection/ResourceLock/MultiLock.cs
  src/KubernetesClient/MuxedStream.cs
  src/KubernetesClient/Watcher.cs
  src/KubernetesClient/WatcherExt.cs
  src/LibKubernetesGenerator/ApiGenerator.cs
  src/LibKubernetesGenerator/ClassNameHelper.cs
  src/LibKubernetesGenerator/GeneralNameHelper.cs
  src/LibKubernetesGenerator/KubernetesClientSourceGenerator.cs
  src/LibKubernetesGenerator/MetaHelper.cs
  src/LibKubernetesGenerator/ModelExtGenerator.cs
  src/LibKubernetesGenerator/ParamHelper.cs
  src/LibKubernetesGenerator/PluralHelper.cs
  src/LibKubernetesGenerator/StringHelpers.cs
  src/LibKubernetesGenerator/TypeHelper.cs
  src/LibKubernetesGenerator/UtilHelper.cs
  tests/KubernetesClient.Tests/ItemsEnumTests.cs
  tests/KubernetesClient.Tests/KubernetesExecTests.cs
  tests/KubernetesClient.Tests/KubernetesYamlTests.cs
  tests/KubernetesClient.Tests/ModelExtensionTests.cs
Labels: cncf-cla: yes, size/L, lgtm, approved

#1039 fix build warning of ThisAssembly
  src/KubernetesClient.Basic/GeneratedApiVersion.cs
Labels: size/XS, cncf-cla: yes, lgtm, approved

#1040 add patch and replace to generic
  src/KubernetesClient/GenericClient.cs
  tests/E2E.Tests/MinikubeTests.cs
Labels: cncf-cla: yes, size/L, lgtm, approved
