Repository kubernetes-client/csharp, pull requests merged in 2022-03, with the labels that each got.

#792 cleanup folders
  examples/Directory.Build.props
  examples/Directory.Build.targets
  examples/GenericKubernetesApi/GenericKubernetesApi.csproj
  examples/attach/attach.csproj
  examples/customResource/CustomResourceDefinition.cs
  examples/customResource/Program.cs
  examples/customResource/cResource.cs
  examples/customResource/customResource.csproj
  examples/exec/exec.csproj
  examples/generic/generic.csproj
  examples/labels/labels.csproj
  examples/logs/logs.csproj
  examples/metrics/metrics.csproj
  examples/namespace/namespace.csproj
  examples/nginx.yml
  examples/patch/patch.csproj
  examples/portforward/portforward.csproj
  examples/prometheus/prometheus.csproj
  examples/simple/simple.csproj
  examples/watch/watch.csproj
  examples/yaml/Program.cs
  examples/yaml/yaml.csproj
  kubernetes-client.sln
  src/KubernetesClient.Util/KubernetesClient.Util.csproj
  src/KubernetesClient/KubernetesClient.csproj
  src/LibKubernetesGenerator/ApiGenerator.cs
  src/LibKubernetesGenerator/ClassNameHelper.cs
  src/LibKubernetesGenerator/GeneralNameHelper.cs
  src/LibKubernetesGenerator/GeneratorExecutionContextExt.cs
  src/LibKubernetesGenerator/INustacheHelper.cs
  src/LibKubernetesGenerator/KubernetesClientSourceGenerator.cs
  src/LibKubernetesGenerator/LibKubernetesGenerator.csproj
  src/LibKubernetesGenerator/MetaHelper.cs
  src/LibKubernetesGenerator/ModelExtGenerator.cs
  src/LibKubernetesGenerator/ModelGenerator.cs
  src/LibKubernetesGenerator/ParamHelper.cs
  src/LibKubernetesGenerator/PluralHelper.cs
  src/LibKubernetesGenerator/StringHelpers.cs
  src/LibKubernetesGenerator/TypeHelper.cs
  src/LibKubernetesGenerator/UtilHelper.cs
  src/LibKubernetesGenerator/VersionConverterGenerator.cs
  src/LibKubernetesGenerator/templates/IKubernetes.cs.template
  src/LibKubernetesGenerator/templates/Kubernetes.cs.template
  src/LibKubernetesGenerator/templates/KubernetesExtensions.cs.template
  src/LibKubernetesGenerator/templates/Model.cs.template
  src/LibKubernetesGenerator/templates/ModelExtensions.cs.template
  tests/KubernetesClient.Util.Tests/KubernetesClient.Util.Tests.csproj
  util/src/KubernetesClient.Util/KubernetesClient.Util.csproj.DotSettings
Labels: cncf-cla: yes, size/L, lgtm, approved

#794 Code Enhancements
  src/KubernetesClient/Autorest/StringTokenProvider.cs
  src/KubernetesClient/IntOrStringConverter.cs
  src/KubernetesClient/Kubernetes.cs
  src/KubernetesClient/KubernetesJson.cs
  src/KubernetesClient/LineSeparatedHttpContent.cs
  src/KubernetesClient/QuantityConverter.cs
  src/KubernetesClient/ResourceQuantity.cs
  src/KubernetesClient/V1PatchJsonConverter.cs
  src/KubernetesClient/V1Status.ObjectView.cs
Labels: cncf-cla: yes, size/M, lgtm

#796 fix release build version schema
  .github/workflows/draft.yaml
  version.json
Labels: size/XS, cncf-cla: yes, lgtm, approved

#799 Enable unnecessary code rules
  .editorconfig
  Directory.Build.props
  src/KubernetesClient/Authentication/ExecTokenProvider.cs
  src/KubernetesClient/Autorest/BasicAuthenticationCredentials.cs
  src/KubernetesClient/Autorest/HttpExtensions.cs
  src/KubernetesClient/Autorest/HttpMessageWrapper.cs
  src/KubernetesClient/Autorest/HttpOperationException.cs
  src/KubernetesClient/Autorest/HttpOperationResponse.cs
  src/KubernetesClient/Autorest/HttpRequestMessageWrapper.cs
  src/KubernetesClient/Autorest/HttpResponseMessageWrapper.cs
  src/KubernetesClient/Autorest/RestException.cs
  src/KubernetesClient/Autorest/TokenCredentials.cs
  src/KubernetesClient/CertUtils.cs
  src/KubernetesClient/Kubernetes.ConfigInit.cs
  src/KubernetesClient/Kubernetes.cs
  src/KubernetesClient/KubernetesList.cs
  src/KubernetesClient/Watcher.cs
  src/LibKubernetesGenerator/ApiGenerator.cs
  src/LibKubernetesGenerator/GeneralNameHelper.cs
  src/LibKubernetesGenerator/GeneratorExecutionContextExt.cs
  src/LibKubernetesGenerator/KubernetesClientSourceGenerator.cs
  src/LibKubernetesGenerator/ModelExtGenerator.cs
  src/LibKubernetesGenerator/ModelGenerator.cs
  src/LibKubernetesGenerator/UtilHelper.cs
  tests/KubernetesClient.Tests/StreamDemuxerTests.cs
  tests/KubernetesClient.Tests/Util/Informer/Cache/CacheTest.cs
  tests/KubernetesClient.Tests/Util/Informer/Cache/ListerTest.cs
Labels: cncf-cla: yes, size/L, lgtm, approved

#800 Support for package icon file
  logo.png
  src/KubernetesClient/KubernetesClient.csproj
Labels: size/XS, cncf-cla: yes, lgtm, approved

#807 move getheader to abstract
  src/KubernetesClient.Basic/AbstractKubernetes.cs
  src/KubernetesClient/Kubernetes.Header.cs
Labels: cncf-cla: yes, size/M, lgtm, approved

#806 move kubectl config and yaml related to model module
  examples/yaml/Program.cs
  src/KubernetesClient.Basic/Global.cs
  src/KubernetesClient.Models/IntOrStringJsonConverter.cs
  src/KubernetesClient.Models/IntOrStringYamlConverter.cs
  src/KubernetesClient.Models/IntstrIntOrString.cs
  src/KubernetesClient.Models/KubeConfigModels/AuthProvider.cs
  src/KubernetesClient.Models/KubeConfigModels/Cluster.cs
  src/KubernetesClient.Models/KubeConfigModels/ClusterEndpoint.cs
  src/KubernetesClient.Models/KubeConfigModels/Context.cs
  src/KubernetesClient.Models/KubeConfigModels/ContextDetails.cs
  src/KubernetesClient.Models/KubeConfigModels/ExecCredentialResponse.cs
  src/KubernetesClient.Models/KubeConfigModels/ExternalExecution.cs
  src/KubernetesClient.Models/KubeConfigModels/K8SConfiguration.cs
  src/KubernetesClient.Models/KubeConfigModels/NamedExtension.cs
  src/KubernetesClient.Models/KubeConfigModels/User.cs
  src/KubernetesClient.Models/KubeConfigModels/UserCredentials.cs
  src/KubernetesClient.Models/KubernetesClient.Models.csproj
  src/KubernetesClient.Models/KubernetesJson.cs
  src/KubernetesClient.Models/KubernetesObject.cs
  src/KubernetesClient.Models/KubernetesYaml.cs
  src/KubernetesClient.Models/ResourceQuantity.cs
  src/KubernetesClient.Models/ResourceQuantityJsonConverter.cs
  src/KubernetesClient.Models/ResourceQuantityYamlConverter.cs
  src/KubernetesClient.Models/StringQuotingEmitter.cs
  src/KubernetesClient/KubernetesClient.csproj
  src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs
  tests/KubernetesClient.Tests/KubernetesClientConfigurationTests.cs
  tests/KubernetesClient.Tests/KubernetesYamlTests.cs
  tests/KubernetesClient.Tests/QuantityValueTests.cs
Labels: cncf-cla: yes, size/L, lgtm, approved

#810 Standardize TargetFramwork for VisualStudio IDE
  Directory.Build.props
  README.md
  examples/Directory.Build.props
  src/KubernetesClient.Basic/KubernetesClient.Basic.csproj
  src/KubernetesClient.Models/KubernetesClient.Models.csproj
  src/KubernetesClient/KubernetesClient.csproj
  src/LibKubernetesGenerator/LibKubernetesGenerator.csproj
  src/nuget.proj
  tests/E2E.Tests/E2E.Tests.csproj
  tests/KubernetesClient.Tests/KubernetesClient.Tests.csproj
  tests/KubernetesClient.Util.Tests/KubernetesClient.Util.Tests.csproj
Labels: cncf-cla: yes, size/L, lgtm

#811 Reuse const strings and expose PluralName
  src/LibKubernetesGenerator/templates/ModelExtensions.cs.template
Labels: size/XS, cncf-cla: yes, lgtm
