Repository kubernetes-client/csharp, pull requests merged in 2023-04, with the labels that each got.

#1257 Add AddJsonOptions to KubernetesClientConfiguration and KubernetesJson
  examples/prometheus/Prometheus.cs
  src/KubernetesClient.Models/KubernetesJson.cs
  src/KubernetesClient/Kubernetes.ConfigInit.cs
  src/KubernetesClient/Kubernetes.cs
  src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs
  src/KubernetesClient/KubernetesClientConfiguration.cs
  tests/KubernetesClient.Tests/SerializationTests.cs
  tests/KubernetesClient.Tests/WatchTests.cs
Labels: cncf-cla: yes, size/L, lgtm, approved

#1261 Use the system certificate store if no certificates are specified.
  src/KubernetesClient/Kubernetes.ConfigInit.cs
  tests/KubernetesClient.Tests/KubernetesClientConfigurationTests.cs
  tests/KubernetesClient.Tests/assets/kubeconfig.tls-no-skip.yml
Labels: cncf-cla: yes, size/M, lgtm, approved

#1274 feat: Add a parameter to the GenericClient class that configures the …
  src/KubernetesClient/GenericClient.cs
Labels: cncf-cla: yes, size/S, lgtm, approved

#1282 Support TLS Server Name overrides in kubeconfig
  src/KubernetesClient.Models/KubeConfigModels/ClusterEndpoint.cs
  src/KubernetesClient/Kubernetes.ConfigInit.cs
  src/KubernetesClient/Kubernetes.cs
  src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs
  src/KubernetesClient/KubernetesClientConfiguration.cs
  tests/KubernetesClient.Tests/KubernetesClientConfigurationTests.cs
  tests/KubernetesClient.Tests/assets/kubeconfig.tls-servername.yml
Labels: cncf-cla: yes, size/M, lgtm, approved
