Repository kubernetes-client/csharp, pull requests merged in 2023-12, with the labels that each got.

#1463 Move to net8.0
  .github/workflows/buildtest.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/docfx.yaml
  .github/workflows/draft.yaml
  .github/workflows/nuget.yaml
  Directory.Build.targets
  examples/Directory.Build.props
  examples/openTelemetryConsole/openTelemetryConsole.csproj
  global.json
  kubernetes-client.sln
  src/KubernetesClient.Kubectl/KubernetesClient.Kubectl.csproj
  src/KubernetesClient.ModelConverter/KubernetesClient.ModelConverter.csproj
  src/KubernetesClient/KubernetesClient.csproj
  tests/E2E.Tests/E2E.Tests.csproj
  tests/Kubectl.Tests/Kubectl.Tests.csproj
  tests/KubernetesClient.Classic.Tests/KubernetesClient.Classic.Tests.csproj
  tests/KubernetesClient.Tests/KubernetesClient.Tests.csproj
  tests/KubernetesClient.Tests/WatchTests.cs
  version.json
Labels: cncf-cla: yes, size/L, lgtm, approved

#1464 Updated OpenTelemetry.Instrumentation.Http from version 1.0.0-rc9.14 to 1.6.0-beta.3
  examples/openTelemetryConsole/openTelemetryConsole.csproj
Labels: size/XS, cncf-cla: yes, lgtm, approved

#1468 Improve docs and naming of `LeaderElector` methods.
  src/KubernetesClient/LeaderElection/LeaderElector.cs
  tests/KubernetesClient.Tests/LeaderElection/LeaderElectionTests.cs
Labels: cncf-cla: yes, size/M, lgtm, approved
