Repository kubernetes-client/csharp, pull requests merged in 2023-07, with the labels that each got.

#1343 Change X509Certificate2 constructor to fix KB5025823
  src/KubernetesClient/CertUtils.cs
  src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs
Labels: cncf-cla: yes, size/S, lgtm, approved

#1332 fix: yaml with merge
  src/KubernetesClient.Models/KubernetesYaml.cs
  tests/KubernetesClient.Tests/KubernetesYamlTests.cs
Labels: cncf-cla: yes, size/L, lgtm, approved

#1352 fix warnings by xunit
  tests/KubernetesClient.Tests/AuthTests.cs
  tests/KubernetesClient.Tests/LeaderElection/LeaderElectionTests.cs
  tests/KubernetesClient.Tests/ModelExtensionTests.cs
  tests/KubernetesClient.Tests/OidcAuthTests.cs
Labels: cncf-cla: yes, size/M, lgtm, approved
