Repository kubernetes-client/csharp, pull requests merged in 2023-10, with the labels that each got.

#1415 align auth provider with go-client
  src/KubernetesClient.Classic/KubernetesClient.Classic.csproj
  src/KubernetesClient/Authentication/GcpTokenProvider.cs
  src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs
  tests/KubernetesClient.Tests/GcpTokenProviderTests.cs
Labels: cncf-cla: yes, size/L, lgtm, approved

#1426 fix docfx generate error
  .github/workflows/docfx.yaml
  doc/docfx.json
Labels: size/XS, cncf-cla: yes, lgtm, approved

#1420 Prevent UnobservedTaskException in LeaderElector
  src/KubernetesClient/LeaderElection/LeaderElector.cs
Labels: size/XS, cncf-cla: yes, lgtm, approved

#1427 update docfx to nunit owned
  .github/workflows/docfx.yaml
Labels: size/XS, cncf-cla: yes, lgtm, approved

#1428 folder structure clean up
  src/KubernetesClient.Basic/AssemblyInfo.cs
  src/KubernetesClient.Basic/Global.cs
  src/KubernetesClient.Classic/KubernetesClient.Classic.csproj
  src/KubernetesClient.Models/AssemblyInfo.cs
  src/KubernetesClient.Models/Global.cs
  src/KubernetesClient/AbstractKubernetes.cs
  src/KubernetesClient/Autorest/HttpExtensions.cs
  src/KubernetesClient/Autorest/HttpMessageWrapper.cs
  src/KubernetesClient/Autorest/HttpOperationException.cs
  src/KubernetesClient/Autorest/HttpOperationResponse.cs
  src/KubernetesClient/Autorest/HttpRequestMessageWrapper.cs
  src/KubernetesClient/Autorest/HttpResponseMessageWrapper.cs
  src/KubernetesClient/Extensions.cs
  src/KubernetesClient/FloatEmitter.cs
  src/KubernetesClient/GeneratedApiVersion.cs
  src/KubernetesClient/IItems.cs
  src/KubernetesClient/IKubernetesObject.cs
  src/KubernetesClient/IMetadata.cs
  src/KubernetesClient/ISpec.cs
  src/KubernetesClient/IStatus.cs
  src/KubernetesClient/IValidate.cs
  src/KubernetesClient/KubeConfigModels/AuthProvider.cs
  src/KubernetesClient/KubeConfigModels/Cluster.cs
  src/KubernetesClient/KubeConfigModels/ClusterEndpoint.cs
  src/KubernetesClient/KubeConfigModels/Context.cs
  src/KubernetesClient/KubeConfigModels/ContextDetails.cs
  src/KubernetesClient/KubeConfigModels/ExecCredentialResponse.cs
  src/KubernetesClient/KubeConfigModels/ExternalExecution.cs
  src/KubernetesClient/KubeConfigModels/K8SConfiguration.cs
  src/KubernetesClient/KubeConfigModels/NamedExtension.cs
  src/KubernetesClient/KubeConfigModels/User.cs
  src/KubernetesClient/KubeConfigModels/UserCredentials.cs
  src/KubernetesClient/KubernetesClient.csproj
  src/KubernetesClient/KubernetesJson.cs
  src/KubernetesClient/KubernetesObject.cs
  src/KubernetesClient/KubernetesYaml.cs
  src/KubernetesClient/Models/ContainerMetrics.cs
  src/KubernetesClient/Models/GeneratedModelVersion.cs
  src/KubernetesClient/Models/IntOrStringJsonConverter.cs
  src/KubernetesClient/Models/IntOrStringYamlConverter.cs
  src/KubernetesClient/Models/IntstrIntOrString.cs
  src/KubernetesClient/Models/KubernetesEntityAttribute.cs
  src/KubernetesClient/Models/KubernetesList.cs
  src/KubernetesClient/Models/ModelExtensions.cs
  src/KubernetesClient/Models/ModelVersionConverter.cs
  src/KubernetesClient/Models/NodeMetrics.cs
  src/KubernetesClient/Models/NodeMetricsList.cs
  src/KubernetesClient/Models/PodMetrics.cs
  src/KubernetesClient/Models/PodMetricsList.cs
  src/KubernetesClient/Models/ResourceQuantity.cs
  src/KubernetesClient/Models/ResourceQuantityJsonConverter.cs
  src/KubernetesClient/Models/ResourceQuantityYamlConverter.cs
  src/KubernetesClient/Models/V1Patch.cs
  src/KubernetesClient/Models/V1PatchJsonConverter.cs
  src/KubernetesClient/Models/V1PodTemplateSpec.cs
  src/KubernetesClient/Models/V1Status.ObjectView.cs
  src/KubernetesClient/Models/V1Status.cs
  src/KubernetesClient/StringQuotingEmitter.cs
Labels: cncf-cla: yes, size/L, lgtm, approved

#1437 full clone cacert from config object
  src/KubernetesClient/Kubernetes.ConfigInit.cs
Labels: cncf-cla: yes, size/S, lgtm, approved

#1439 fix crd code er
  examples/customResource/Program.cs
Labels: size/XS, cncf-cla: yes, lgtm, approved
