Repository kubernetes-client/csharp, pull requests merged in 2024-01, with the labels that each got.

#1481 fix warnings for net8
  src/KubernetesClient/Autorest/HttpOperationException.cs
  src/KubernetesClient/KubernetesException.cs
  src/KubernetesClient/LeaderElection/LeaderElector.cs
  tests/E2E.Tests/MinikubeTests.cs
  tests/KubernetesClient.Classic.Tests/SimpleTests.cs
  tests/KubernetesClient.Tests/AuthTests.cs
  tests/KubernetesClient.Tests/ByteBufferTests.cs
  tests/KubernetesClient.Tests/KubernetesClientConfigurationTests.cs
  tests/KubernetesClient.Tests/KubernetesExecTests.cs
  tests/KubernetesClient.Tests/KubernetesMetricsTests.cs
  tests/KubernetesClient.Tests/KubernetesYamlTests.cs
  tests/KubernetesClient.Tests/LeaderElection/LeaderElectionTests.cs
  tests/KubernetesClient.Tests/OidcAuthTests.cs
  tests/KubernetesClient.Tests/PodExecTests.cs
  tests/KubernetesClient.Tests/SerializationTests.cs
  tests/KubernetesClient.Tests/StreamDemuxerTests.cs
  tests/KubernetesClient.Tests/TokenFileAuthTests.cs
  tests/KubernetesClient.Tests/WatchTests.cs
Labels: cncf-cla: yes, size/L, lgtm, approved

#1500 Fixed GenericClient not propagating parameters into WatchAsync
  src/KubernetesClient/GenericClient.cs
Labels: size/XS, cncf-cla: yes, lgtm, approved

#1504 Pass CancellationToken from StreamConnectAsync to webSocketBuilder.BuildAndConnectAsync
  src/KubernetesClient/Kubernetes.WebSocket.cs
Labels: size/XS, cncf-cla: yes, lgtm, approved

#1497 introduce slngen and remove stale proj
  .gitignore
  Directory.Build.props
  README.md
  examples/GenericKubernetesApi/GenericKubernetesApi.csproj
  examples/GenericKubernetesApi/Program.cs
  kubernetes-client.proj
  kubernetes-client.sln
Labels: cncf-cla: yes, size/XL, lgtm, approved

#1509 Let `Microsoft.VisualStudio.SlnGen` dependency development only
  Directory.Build.props
Labels: size/XS, cncf-cla: yes, lgtm, approved
