Repository kubernetes-client/csharp, pull requests merged in 2024-02, with the labels that each got.

#1457 Fix: Exec provider potential deadlock
  src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs
Labels: cncf-cla: yes, size/S, lgtm, approved

#1513 add a devcontainer
  .devcontainer/devcontainer.json
Labels: size/XS, cncf-cla: yes, lgtm, approved

#1516 Delete kubernetes-client.sln file
  kubernetes-client.sln
Labels: cncf-cla: yes, size/M, lgtm, approved

#1515 consolidate nuget System.IdentityModel.Tokens.Jwt and YamlDotNet
  src/KubernetesClient.Aot/KubernetesClient.Aot.csproj
  src/KubernetesClient.Classic/KubernetesClient.Classic.csproj
Labels: cncf-cla: yes, size/S, lgtm, approved

#1514 Update Version Compatibility in readme
  README.md
Labels: cncf-cla: yes, size/M, lgtm, approved

#1523 add AKS with kubelogin + MSI example
  examples/aks-kubelogin/Program.cs
  examples/aks-kubelogin/README.md
  examples/aks-kubelogin/aks-kubelogin.csproj
Labels: cncf-cla: yes, size/M, lgtm, approved

#1524 Update project references to include .csproj files instead of .proj files
  kubernetes-client.proj
Labels: size/XS, cncf-cla: yes, lgtm, approved

#1526 Removing prometheus-net dependency
  README.md
  examples/prometheus/Prometheus.cs
  examples/prometheus/prometheus.csproj
  src/KubernetesClient/KubernetesClient.csproj
  src/KubernetesClient/PrometheusHandler.cs
Labels: cncf-cla: yes, size/L, lgtm, approved

#1527 docs: update README.md
  README.md
Labels: size/XS, cncf-cla: yes, lgtm, approved

#1529 fix docfx build
  .github/workflows/docfx.yaml
Labels: size/XS, cncf-cla: yes, lgtm, approved
