Repository kubernetes-client/csharp, pull requests merged in 2024-09, with the labels that each got.

#1577 update `InternalsVisibleTo` usage
  src/KubernetesClient.Classic/AssemblyInfo.cs
  src/KubernetesClient.Classic/KubernetesClient.Classic.csproj
  src/KubernetesClient.ModelConverter/AssemblyInfo.cs
  src/KubernetesClient.ModelConverter/KubernetesClient.ModelConverter.csproj
  src/KubernetesClient/AssemblyInfo.cs
  src/KubernetesClient/KubernetesClient.csproj
Labels: cncf-cla: yes, size/M, lgtm, approved

#1582 configure write permission for draft release action
  .github/workflows/draft.yaml
Labels: size/XS, cncf-cla: yes, lgtm, approved

#1583 Configure permissions for codeql action
  .github/workflows/codeql-analysis.yml
Labels: size/XS, cncf-cla: yes, lgtm, approved

#1585 Added OnError event to MetaObjectLock
  src/KubernetesClient/LeaderElection/ResourceLock/MetaObjectLock.cs
Labels: cncf-cla: yes, size/S, lgtm, approved
