Repository kubernetes-client/csharp, pull requests merged in 2024-04, with the labels that each got.

#1544 Lock usage of YamlDotNet Serializer and Deserializer
  src/KubernetesClient/KubernetesYaml.cs
Labels: cncf-cla: yes, size/M, lgtm, approved

#1530 SlnGen instructions are potentially incomplete
  README.md
Labels: size/XS, cncf-cla: yes, lgtm, approved

#1546 Refactor LibKubernetesGenerator code structure
  src/LibKubernetesGenerator/ApiGenerator.cs
  src/LibKubernetesGenerator/ClassNameHelper.cs
  src/LibKubernetesGenerator/GeneralNameHelper.cs
  src/LibKubernetesGenerator/GeneratorExecutionContextExt.cs
  src/LibKubernetesGenerator/INustacheHelper.cs
  src/LibKubernetesGenerator/IScriptObjectHelper.cs
  src/LibKubernetesGenerator/KubernetesClientSourceGenerator.cs
  src/LibKubernetesGenerator/LibKubernetesGenerator.target
  src/LibKubernetesGenerator/MetaHelper.cs
  src/LibKubernetesGenerator/ModelExtGenerator.cs
  src/LibKubernetesGenerator/ModelGenerator.cs
  src/LibKubernetesGenerator/ParamHelper.cs
  src/LibKubernetesGenerator/PluralHelper.cs
  src/LibKubernetesGenerator/ScriptObjectFactory.cs
  src/LibKubernetesGenerator/StringHelpers.cs
  src/LibKubernetesGenerator/TypeHelper.cs
  src/LibKubernetesGenerator/UtilHelper.cs
  src/LibKubernetesGenerator/templates/AbstractKubernetes.cs.template
  src/LibKubernetesGenerator/templates/IBasicKubernetes.cs.template
  src/LibKubernetesGenerator/templates/IOperations.cs.template
  src/LibKubernetesGenerator/templates/Model.cs.template
  src/LibKubernetesGenerator/templates/ModelExtensions.cs.template
  src/LibKubernetesGenerator/templates/Operations.cs.template
  src/LibKubernetesGenerator/templates/OperationsExtensions.cs.template
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#1552 Add missing Dispose() calls
  src/KubernetesClient/Kubernetes.cs
Labels: size/XS, cncf-cla: yes, lgtm, approved
