Repository kubernetes-client/csharp, pull requests merged in 2025-04, with the labels that each got.

#1621 Add tests to #1618
  Directory.Packages.props
  src/KubernetesClient/Authentication/OidcTokenProvider.cs
  src/KubernetesClient/KubernetesClient.csproj
  tests/KubernetesClient.Tests/KubernetesClient.Tests.csproj
  tests/KubernetesClient.Tests/OidcAuthTests.cs
Labels: cncf-cla: yes, size/L, lgtm, approved

#1623 fix typo
  src/KubernetesClient/WatcherExt.cs
Labels: size/XS, cncf-cla: yes, lgtm, approved

#1625 Remove IdentityModel package versions from Directory.Packages.props
  Directory.Packages.props
  src/KubernetesClient.Classic/KubernetesClient.Classic.csproj
Labels: size/XS, cncf-cla: yes, lgtm, approved

#1628 Clean up warnings in examples
  Directory.Build.props
  examples/attach/Attach.cs
  examples/csrApproval/Program.cs
  examples/exec/Exec.cs
  examples/generic/Generic.cs
  examples/labels/PodList.cs
  examples/logs/Logs.cs
  examples/metrics/Program.cs
  examples/namespace/NamespaceExample.cs
  examples/openTelemetryConsole/Program.cs
  examples/patch/Program.cs
  examples/portforward/PortForward.cs
  examples/simple/PodList.cs
  examples/watch/Program.cs
  examples/webApiDependencyInjection/Controllers/ExampleDependencyInjectionOnConstructorController.cs
  examples/webApiDependencyInjection/Controllers/ExampleDependencyInjectionOnMethodController.cs
  examples/yaml/Program.cs
Labels: cncf-cla: yes, size/XL, lgtm, approved
